apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: breakable-ivory-warbler
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: breakable-ivory-warbler 
  name: breakable-ivory-warbler
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: breakable-ivory-warbler
    weight: 100 
