apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: breakable-ivory-warbler
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: breakable-ivory-warbler 
  name: breakable-ivory-warbler
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: breakable-ivory-warbler 
